function Hd = LPFilt_ForEnv_25_FIR_LeastSqu_ord1000
%LPFILT_FORENV_25_FIR_LEASTSQU_ORD1000 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 12-May-2020 00:48:22

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N     = 1000;  % Order
Fpass = 23;    % Passband Frequency
Fstop = 25;    % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 1;     % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
