% This BP filter is designed to filter the EEG data (fs = 250Hz) in some
% low-freq narrow-bands.
function Hd = BP_filter_fs250_order300(Fstop1,Fpass1,Fpass2,Fstop2)
%BP2TO4HZ_FILTER_FS250_ORDER300 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 05-Jun-2020 00:38:58

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N      = 300;  % Order
% Fstop1 = 1;    % First Stopband Frequency
% Fpass1 = 2;    % First Passband Frequency
% Fpass2 = 4;    % Second Passband Frequency
% Fstop2 = 5;    % Second Stopband Frequency
Wstop1 = 1;    % First Stopband Weight
Wpass  = 1;    % Passband Weight
Wstop2 = 1;    % Second Stopband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
