function Hd = BPF_Gaussian_fs250_order100(Fc1,Fc2)
%BPF_GAUSSIAN_FS250_ORDER100 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 05-Jun-2020 01:26:27

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

N     = 100;      % Order
% Fc1   = 12;       % First Cutoff Frequency
% Fc2   = 14;       % Second Cutoff Frequency
flag  = 'scale';  % Sampling Flag
Alpha = 2;        % Window Parameter
% Create the window vector for the design algorithm.
win = gausswin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);
Hd = Hd.Numerator;

% [EOF]
